### ISSUE TITLE
Semantic error in openapi.yaml

### ISSUE THREAD

**Issue by WilliammDev** [PacktPublishing/Modern-API-Development-with-Spring-6-and-Spring-Boot-3#8]
I see two Semantic errors at line 852 and 1132 in openapiyml file, this error show clearly when you open this file in https://editor.swagger.io/
So please take a look
![image](https://github.com/PacktPublishing/Modern-API-Development-with-Spring-6-and-Spring-Boot-3/assets/159399335/eaf5ada6-7333-4bf4-b516-91ff05dbda0e)
![image](https://github.com/PacktPublishing/Modern-API-Development-with-Spring-6-and-Spring-Boot-3/assets/159399335/b54b5815-4b58-4099-9674-e802f32e8ae1)

**Comment by sharmasourabh** [comment]
Let's discuss the structural error first. `BigDecimal` is not internal type and therefore editor asking to replace it with one of the allowed values. It can be ignored, because we are using the type mapping. You can find the `typeMapping` in file `resources/api/config.json`. This type mapping makes sure that once the OpenApi generator runs, it will pick the BigDecimal from associated type from `config.json` file.

Semantic error for DELETE is there because in ideal scenario you can't have request body associated with DELETE request. However, it was on purpose added here and, beside that API implementation also supports having a request body with DELETE. Therefore, you can also ignore this.
[RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html) and [RFC 7231](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.5) also suggest that a purpose with supporting implementation is OK.
Spotify APIs also has a request body associated with one of the [DELETE request](https://developer.spotify.com/documentation/web-api/reference/remove-tracks-playlist).
Also, in code implementation of this delete method in file `java/com/packt/modern/api/controller/AuthController.java` clearly specifies that you can retrieve the refresh token from the user ID part of the request. You may want to change the specs and implementation if you don't want requestbody in this case.

**Comment by bsingha27** [comment]
Hi @WilliammDev,
We're closing this issue! If you face any further issues on any chapter, please feel free to open a new one.
Thanks.
